steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '>=16.x'
      checkLatest: true

  - task: YarnInstaller@0
    displayName: 'Install Yarn'
    inputs:
      versionSpec: 1.22.x
      checkLatest: false
      includePrerelease: false
