pr:
  - master

trigger: none

variables:
  - template: .devops/templates/variables.yml
  - group: pongo-variables

pool: Default

jobs:
  - job: BuildTestLint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn checkchange
        displayName: verify change files

      - script: |
          yarn lint
        displayName: lint

      - script: |
          yarn build
        displayName: build

      - script: |
          yarn test
        displayName: test

  - job: Chromatic
    displayName: Check for visual regressions 👁️
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          cd apps && cd vr-tests
        displayName: navigating to directory

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn chromatic --project-token=$(chromaticKey)
        displayName: chromatic
