pr:
  - master

trigger: none

variables:
  - template: .devops/templates/variables.yml
  - group: pongo-variables

pool: Default

jobs:
  - job: BuildTestLint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn checkchange
        displayName: verify change files

      - script: |
          yarn lint
        displayName: lint
        env:
          NX_BRANCH: $(pullRequestNumber)

      - script: |
          yarn build
        displayName: build
        env:
          NX_BRANCH: $(pullRequestNumber)

      - script: |
          yarn test
        displayName: test
        env:
          NX_BRANCH: $(pullRequestNumber)

  - job: Chromatic
    displayName: Check for visual regressions 👁️
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          cd apps && cd vr-tests
        displayName: navigating to directory

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn chromatic --project-token=$(chromaticKey)
        displayName: chromatic

  - job: BundleSize
    displayName: Compare Bundle Size 📦
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn bundle-size
        displayName: bundle-size

      - script: |
          yarn bundle-size compare-reports --branch=$(System.PullRequest.TargetBranch) --output=markdown --verbose
        displayName: compare bundle size with base (PR only)
        condition: eq(variables.isPR, true)
