flags:
  react-button:
    paths:
      - packages/pongo-ui/packages/react-button
    carryforward: true

coverage:
  status:
    project:
      default:
        flags:
          - react-button
      react-button:
        flags:
          - react-button

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no
