coverage:
  status:
    project:
      default: off
      react-button:
        target: auto
        flags:
          - react-button

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

flags:
  react-button:
    paths:
      - packages/pongo-ui/packages/react-button
