import * as React from 'react';
import { makeStyles } from '@fluentui/react-make-styles';
import { Text } from '@pongoai/react-text';
import Image from 'next/image';
import { Rating } from '@pongoai/react-rating';
import { VerifiedIcon } from '../ReviewPanel/reviewPanelIcons';
const useStyles = makeStyles({
  reviewCardContianer: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    padding: '25px',
    marginBottom: '20px',
    zIndex: 'inherit',
    opacity: '1',
  },
  customerInfoContainer: { display: 'flex', marginTop: '5px' },
  customerImageContainer: { width: '54px', height: '54px', position: 'relative' },
  customerNameContainer: { marginTop: '17px', marginLeft: '5px' },
  verifiedContainer: { marginTop: '17px', width: '24px', height: '24px', position: 'relative', marginLeft: '5px' },
  socialsFlexbox: { marginLeft: 'auto', display: 'flex', marginTop: '2px', marginRight: '5px' },
  socialsImage: { width: '25px', height: '25px', position: 'relative', marginLeft: '20px' },
  ratingContainer: { display: 'flex' },
  npsContainer: {
    width: '30px',
    height: '30px',
    marginLeft: '7px',
    position: 'relative',
    top: '1px ',
    marginBottom: '5px',
  },
  reviewInfoText: { color: '#636364', top: '12px', position: 'relative', marginLeft: '10px' },
});

type PublicReviewCardProps = {
  //Name of the customer who left the review
  customerName: string;

  //Rating (0-5) the customer gave the the product being reviewed
  starRating: number;

  //path to an image of the customer who left the review
  profileImg: string;

  //Boolean identifying wether or not the customer who left this review is verified
  isVerified: boolean;

  //Location of the customer, expected in display format
  location: string;

  //Time the customer left the review, expected in display format
  timestamp: string;

  //Body content of the customer's review
  reviewText: string;

  //The review's unique ID, generated by the database
  id: string;
};

export const PublicReviewCard = (props: PublicReviewCardProps) => {
  const styles = useStyles();

  return (
    <div className={styles.reviewCardContianer}>
      <div className={styles.customerInfoContainer}>
        <div className={styles.customerImageContainer}>
          <Image src={props.profileImg} alt="profile-image" layout="fill" />
        </div>

        <div className={styles.customerNameContainer}>
          <Text weight="bold" size={500}>
            {props.customerName}
          </Text>
        </div>
        {props.isVerified ? (
          <div className={styles.verifiedContainer}>
            <VerifiedIcon />
          </div>
        ) : (
          <div></div>
        )}
      </div>

      <div className={styles.ratingContainer}>
        <Rating value={props.starRating} />
        <Text weight="light" className={styles.reviewInfoText}>
          {props.location} - {props.timestamp}
        </Text>
      </div>

      <Text size={400}>{props.reviewText}</Text>
    </div>
  );
};
