import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Header } from '../components/Header';
import { FluentProvider } from '@fluentui/react-provider';
import { Button } from '@pongoai/react-button';
import { Link as StyledLink } from '@pongoai/react-link';
import { webLightTheme } from '@pongoai/react-theme';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <FluentProvider theme={webLightTheme}>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>Pongo AI</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main className={styles.main}>
          <StyledLink href="/reviews">Home</StyledLink>
          <Link href="/">Home</Link>
          <Link href="/reviews">Reviews</Link>
          <Link href="/share">Share</Link>
          <Link href="/settings">Settings</Link>
          <Button>This is a button</Button>
        </main>
      </div>
    </FluentProvider>
  );
};

export default Home;
