import type { NextPage } from 'next';
import Head from 'next/head';
import { FluentProvider } from '@fluentui/react-provider';
import { Button } from '@pongoai/react-button';
import { webLightTheme } from '@pongoai/react-theme';
import { Header, Sidebar, Content } from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <FluentProvider theme={webLightTheme}>
      <Header />
      <Sidebar activePage="home" />
      <div>
        <Head>
          <title>Pongo AI</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main className={styles.main}>
          <Content>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nunc nunc. Etiam nec purus id dui
            bibendum efficitur ac nec arcu. Ut luctus quam a dictum ullamcorper. Etiam viverra erat in elementum
            sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. In gravida dapibus diam, non
            semper arcu. Quisque sit amet feugiat sapien. Nam vel mauris eget nisi volutpat pretium. Integer consequat
            velit in turpis iaculis malesuada. Praesent sit amet porttitor nisi. Sed sed ultrices arcu. Nulla facilisi.
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi
            fringilla, dolor quis fringilla scelerisque, velit justo consequat risus, ut finibus magna velit at lorem.
            Fusce volutpat pretium elit et lacinia. Praesent vitae tempus lectus. Ut nisi mi, maximus quis gravida
            imperdiet, fermentum vel elit. Sed nisl mauris, tincidunt ac dictum et, dictum quis felis. Orci varius
            natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas gravida dolor lacus,
            tempor mollis augue vulputate efficitur. Etiam pharetra tellus id ultrices lobortis. Etiam ornare
            pellentesque accumsan. Sed aliquet sed metus ut luctus. In vitae diam volutpat, pretium erat ut, feugiat
            neque. In ullamcorper posuere cursus. Vivamus ac venenatis purus, id varius neque. Nullam et sodales elit,
            ac imperdiet justo. Donec odio lorem, fringilla tempor tellus sed, efficitur facilisis est. Sed fringilla
            lobortis luctus. Sed at libero sem. Duis nisl ex, tempus in dui id, pellentesque porta nunc. Nullam quam
            urna, egestas lobortis lectus a, tristique pharetra orci. Duis dapibus sit amet magna eget varius. Phasellus
            massa leo, feugiat id diam in, semper aliquet lectus. Aliquam tempus urna malesuada elit finibus tincidunt.
            Vivamus nec odio gravida mi sodales ultricies. In hac habitasse platea dictumst. Ut felis mauris, feugiat at
            maximus sed, pretium id mauris. Integer id posuere odio, vitae cursus orci. Praesent consequat in nulla ut
            blandit. Donec eu velit condimentum, vehicula mauris vel, pulvinar leo. Ut vitae dignissim lectus, eget
            finibus dui. Sed eget leo eu neque sagittis posuere. Suspendisse volutpat hendrerit varius. Integer
            tincidunt nunc finibus volutpat tincidunt. Duis fermentum lacus sit amet nisi convallis porta. Nunc a mollis
            turpis. Nulla viverra at orci in ullamcorper. Proin semper est non tincidunt cursus. Duis finibus rutrum
            purus aliquam rutrum. Nunc finibus vel risus in fermentum. Etiam suscipit tincidunt massa, vel feugiat augue
            semper sed. Curabitur id faucibus orci. Praesent nec mauris euismod, eleifend lacus a, aliquet nisl. Ut quam
            nisi, mollis sed lobortis eget, varius vitae massa. Nunc gravida, sapien et vehicula venenatis, nibh arcu
            porta nibh, sit amet finibus mauris metus non ante. Proin elementum odio vel viverra aliquet. Phasellus id
            nisl nec sapien porta lobortis in sit amet massa. Suspendisse luctus non ipsum eu tempus. Suspendisse sed
            lectus ac diam molestie accumsan.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nunc
            nunc. Etiam nec purus id dui bibendum efficitur ac nec arcu. Ut luctus quam a dictum ullamcorper. Etiam
            viverra erat in elementum sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. In
            gravida dapibus diam, non semper arcu. Quisque sit amet feugiat sapien. Nam vel mauris eget nisi volutpat
            pretium. Integer consequat velit in turpis iaculis malesuada. Praesent sit amet porttitor nisi. Sed sed
            ultrices arcu. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
            turpis egestas. Morbi fringilla, dolor quis fringilla scelerisque, velit justo consequat risus, ut finibus
            magna velit at lorem. Fusce volutpat pretium elit et lacinia. Praesent vitae tempus lectus. Ut nisi mi,
            maximus quis gravida imperdiet, fermentum vel elit. Sed nisl mauris, tincidunt ac dictum et, dictum quis
            felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas
            gravida dolor lacus, tempor mollis augue vulputate efficitur. Etiam pharetra tellus id ultrices lobortis.
            Etiam ornare pellentesque accumsan. Sed aliquet sed metus ut luctus. In vitae diam volutpat, pretium erat
            ut, feugiat neque. In ullamcorper posuere cursus. Vivamus ac venenatis purus, id varius neque. Nullam et
            sodales elit, ac imperdiet justo. Donec odio lorem, fringilla tempor tellus sed, efficitur facilisis est.
            Sed fringilla lobortis luctus. Sed at libero sem. Duis nisl ex, tempus in dui id, pellentesque porta nunc.
            Nullam quam urna, egestas lobortis lectus a, tristique pharetra orci. Duis dapibus sit amet magna eget
            varius. Phasellus massa leo, feugiat id diam in, semper aliquet lectus. Aliquam tempus urna malesuada elit
            finibus tincidunt. Vivamus nec odio gravida mi sodales ultricies. In hac habitasse platea dictumst. Ut felis
            mauris, feugiat at maximus sed, pretium id mauris. Integer id posuere odio, vitae cursus orci. Praesent
            consequat in nulla ut blandit. Donec eu velit condimentum, vehicula mauris vel, pulvinar leo. Ut vitae
            dignissim lectus, eget finibus dui. Sed eget leo eu neque sagittis posuere. Suspendisse volutpat hendrerit
            varius. Integer tincidunt nunc finibus volutpat tincidunt. Duis fermentum lacus sit amet nisi convallis
            porta. Nunc a mollis turpis. Nulla viverra at orci in ullamcorper. Proin semper est non tincidunt cursus.
            Duis finibus rutrum purus aliquam rutrum. Nunc finibus vel risus in fermentum. Etiam suscipit tincidunt
            massa, vel feugiat augue semper sed. Curabitur id faucibus orci. Praesent nec mauris euismod, eleifend lacus
            a, aliquet nisl. Ut quam nisi, mollis sed lobortis eget, varius vitae massa. Nunc gravida, sapien et
            vehicula venenatis, nibh arcu porta nibh, sit amet finibus mauris metus non ante. Proin elementum odio vel
            viverra aliquet. Phasellus id nisl nec sapien porta lobortis in sit amet massa. Suspendisse luctus non ipsum
            eu tempus. Suspendisse sed lectus ac diam molestie aLorem ipsum dolor sit amet, consectetur adipiscing elit.
            Mauris eget nunc nunc. Etiam nec purus id dui bibendum efficitur ac nec arcu. Ut luctus quam a dictum
            ullamcorper. Etiam viverra erat in elementum sollicitudin. Interdum et malesuada fames ac ante ipsum primis
            in faucibus. In gravida dapibus diam, non semper arcu. Quisque sit amet feugiat sapien. Nam vel mauris eget
            nisi volutpat pretium. Integer consequat velit in turpis iaculis malesuada. Praesent sit amet porttitor
            nisi. Sed sed ultrices arcu. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et
            malesuada fames ac turpis egestas. Morbi fringilla, dolor quis fringilla scelerisque, velit justo consequat
            risus, ut finibus magna velit at lorem. Fusce volutpat pretium elit et lacinia. Praesent vitae tempus
            lectus. Ut nisi mi, maximus quis gravida imperdiet, fermentum vel elit. Sed nisl mauris, tincidunt ac dictum
            et, dictum quis felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus
            mus. Maecenas gravida dolor lacus, tempor mollis augue vulputate efficitur. Etiam pharetra tellus id
            ultrices lobortis. Etiam ornare pellentesque accumsan. Sed aliquet sed metus ut luctus. In vitae diam
            volutpat, pretium erat ut, feugiat neque. In ullamcorper posuere cursus. Vivamus ac venenatis purus, id
            varius neque. Nullam et sodales elit, ac imperdiet justo. Donec odio lorem, fringilla tempor tellus sed,
            efficitur facilisis est. Sed fringilla lobortis luctus. Sed at libero sem. Duis nisl ex, tempus in dui id,
            pellentesque porta nunc. Nullam quam urna, egestas lobortis lectus a, tristique pharetra orci. Duis dapibus
            sit amet magna eget varius. Phasellus massa leo, feugiat id diam in, semper aliquet lectus. Aliquam tempus
            urna malesuada elit finibus tincidunt. Vivamus nec odio gravida mi sodales ultricies. In hac habitasse
            platea dictumst. Ut felis mauris, feugiat at maximus sed, pretium id mauris. Integer id posuere odio, vitae
            cursus orci. Praesent consequat in nulla ut blandit. Donec eu velit condimentum, vehicula mauris vel,
            pulvinar leo. Ut vitae dignissim lectus, eget finibus dui. Sed eget leo eu neque sagittis posuere.
            Suspendisse volutpat hendrerit varius. Integer tincidunt nunc finibus volutpat tincidunt. Duis fermentum
            lacus sit amet nisi convallis porta. Nunc a mollis turpis. Nulla viverra at orci in ullamcorper. Proin
            semper est non tincidunt cursus. Duis finibus rutrum purus aliquam rutrum. Nunc finibus vel risus in
            fermentum. Etiam suscipit tincidunt massa, vel feugiat augue semper sed. Curabitur id faucibus orci.
            Praesent nec mauris euismod, eleifend lacus a, aliquet nisl. Ut quam nisi, mollis sed lobortis eget, varius
            vitae massa. Nunc gravida, sapien et vehicula venenatis, nibh arcu porta nibh, sit amet finibus mauris metus
            non ante. Proin elementum odio vel viverra aliquet. Phasellus id nisl nec sapien porta lobortis in sit amet
            massa. Suspendisse luctus non ipsum eu tempus. Suspendisse sed lectus ac diam molestie
            accumsan.ccumsan.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nunc nunc. Etiam nec
            purus id dui bibendum efficitur ac nec arcu. Ut luctus quam a dictum ullamcorper. Etiam viverra erat in
            elementum sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. In gravida dapibus
            diam, non semper arcu. Quisque sit amet feugiat sapien. Nam vel mauris eget nisi volutpat pretium. Integer
            consequat velit in turpis iaculis malesuada. Praesent sit amet porttitor nisi. Sed sed ultrices arcu. Nulla
            facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            Morbi fringilla, dolor quis fringilla scelerisque, velit justo consequat risus, ut finibus magna velit at
            lorem. Fusce volutpat pretium elit et lacinia. Praesent vitae tempus lectus. Ut nisi mi, maximus quis
            gravida imperdiet, fermentum vel elit. Sed nisl mauris, tincidunt ac dictum et, dictum quis felis. Orci
            varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas gravida dolor
            lacus, tempor mollis augue vulputate efficitur. Etiam pharetra tellus id ultrices lobortis. Etiam ornare
            pellentesque accumsan. Sed aliquet sed metus ut luctus. In vitae diam volutpat, pretium erat ut, feugiat
            neque. In ullamcorper posuere cursus. Vivamus ac venenatis purus, id varius neque. Nullam et sodales elit,
            ac imperdiet justo. Donec odio lorem, fringilla tempor tellus sed, efficitur facilisis est. Sed fringilla
            lobortis luctus. Sed at libero sem. Duis nisl ex, tempus in dui id, pellentesque porta nunc. Nullam quam
            urna, egestas lobortis lectus a, tristique pharetra orci. Duis dapibus sit amet magna eget varius. Phasellus
            massa leo, feugiat id diam in, semper aliquet lectus. Aliquam tempus urna malesuada elit finibus tincidunt.
            Vivamus nec odio gravida mi sodales ultricies. In hac habitasse platea dictumst. Ut felis mauris, feugiat at
            maximus sed, pretium id mauris. Integer id posuere odio, vitae cursus orci. Praesent consequat in nulla ut
            blandit. Donec eu velit condimentum, vehicula mauris vel, pulvinar leo. Ut vitae dignissim lectus, eget
            finibus dui. Sed eget leo eu neque sagittis posuere. Suspendisse volutpat hendrerit varius. Integer
            tincidunt nunc finibus volutpat tincidunt. Duis fermentum lacus sit amet nisi convallis porta. Nunc a mollis
            turpis. Nulla viverra at orci in ullamcorper. Proin semper est non tincidunt cursus. Duis finibus rutrum
            purus aliquam rutrum. Nunc finibus vel risus in fermentum. Etiam suscipit tincidunt massa, vel feugiat augue
            semper sed. Curabitur id faucibus orci. Praesent nec mauris euismod, eleifend lacus a, aliquet nisl. Ut quam
            nisi, mollis sed lobortis eget, varius vitae massa. Nunc gravida, sapien et vehicula venenatis, nibh arcu
            porta nibh, sit amet finibus mauris metus non ante. Proin elementum odio vel viverra aliquet. Phasellus id
            nisl nec sapien porta lobortis in sit amet massa. Suspendisse luctus non ipsum eu tempus. Suspendisse sed
            lectus ac diam molestie accumsan.
          </Content>
        </main>
      </div>
    </FluentProvider>
  );
};

export default Home;
