import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { FluentProvider } from '@fluentui/react-provider';
import { Button } from '@pongoai/react-button';
import { Search, Select } from '@pongoai/react-textfield';
import { webLightTheme } from '@pongoai/react-theme';
import { Header, Sidebar, Content, DashboardCard } from '../components';

const cards: any = {
  0: {
    name: 'Jeans 1',
    rating: 4.5,
    ratingCount: 30,
  },
  1: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  2: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  3: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  4: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  5: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  6: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  7: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  8: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  9: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  10: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
  11: {
    name: 'Jeans 2',
    rating: 3.2,
    ratingCount: 35,
  },
};

const cardWrapperStyles: React.CSSProperties = {
  display: 'grid',
  gridGap: '30px',
  gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
  justifyItems: 'space-evenly',
  paddingTop: '20px',
  paddingLeft: '20px',
  paddingRight: '20px',
};

const searchTaskBarStyles: React.CSSProperties = {
  height: '68px',
  display: 'flex',
  flexDirection: 'row',
  background: 'white',
  verticalAlign: 'middle',
  alignItems: 'center',
  paddingLeft: '20px',
  paddingRight: '20px',
  boxShadow: 'inset 0px 0px 25px 1px rgba(0, 0, 0, 0.04)',
  gap: '12px',
};

const selectStyles = {
  width: '150px',
  height: '45px',
  zIndex: '1',
};

const searchBarStyles = {
  zIndex: '1',
  height: '45px',
};

const circularBorder = {
  borderRadius: '999px',
};

const buttonStyles = { fontSize: '18px', height: '45px', marginLeft: 'auto' };

const selectOptions = [
  { value: 'Relevance', label: 'Relevance' },
  { value: 'Total', label: 'Total' },
  { value: 'Rating', label: 'Rating' },
];

const Home: NextPage = () => {
  const renderCards = React.useMemo(() => {
    const list = [];

    for (const card in cards) {
      list.push(
        <DashboardCard name={cards[card].name} rating={cards[card].rating} ratingCount={cards[card].ratingCount} />,
      );
    }

    return list;
  }, []);

  return (
    <FluentProvider theme={webLightTheme}>
      <Header />
      <Sidebar activePage="home" />
      <Head>
        <title>Pongo AI</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Content>
        <>
          <div style={searchTaskBarStyles}>
            <Search
              placeholder="Search your surveys..."
              appearance="outlined"
              textFieldBorder={{ style: circularBorder }}
              style={searchBarStyles}
            />
            <Select appearance="outlined" options={selectOptions} style={selectStyles} label="Sort by" />
            <Button appearance="primary" shape="rounded" style={buttonStyles}>
              + New Product
            </Button>
          </div>
          <div style={cardWrapperStyles}>{renderCards}</div>
        </>
      </Content>
    </FluentProvider>
  );
};

export default Home;
