name: 🚀 Publish NPM Changes
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📗 Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags

      - name: 📥 Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ✨ Publishing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn
          git config user.name "pongoaibuild"
          git config user.email "https://github.com/pongoaibuild/pongoai-frontend"
          git remote set-url origin https://pongoaibuild:${{ secrets.GITHUB_TOKEN }}@github.com/PongoAI/pongoai-frontend.git
          yarn publish:beachball -n ${{secrets.NPM_TOKEN}}
