name: Releasing v0_$(Date:yyyyMMdd)$(Rev:.r)

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 'Publish 🚀'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Publishing ✨
        uses: ./
        with:
            run: yarn publish:beachball -n ${{secrets.NPM_TOKEN}}
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
